"""
    read_vel(filepath::String)

Parse data from `.vel` file.

# Positional Arguments
- `filepath`: `String` path to `.vel` file

# Returns
- `vel`: `VelData` object containing the velocity information generated by MIDAS
"""
function read_vel(filepath::String)
    open(filepath, "r") do io
        str = readline(io)
        tokens = split(str)
        vel = VelData(
            tokens[1],
            tokens[2],
            parse(Float64, tokens[3]),
            parse(Float64, tokens[4]),
            parse(Float64, tokens[5]),
            parse(Int, tokens[6]),
            parse(Int, tokens[7]),
            parse(Int, tokens[8]),
            parse(Float64, tokens[9]),
            parse(Float64, tokens[10]),
            parse(Float64, tokens[11]),
            parse(Float64, tokens[12]),
            parse(Float64, tokens[13]),
            parse(Float64, tokens[14]),
            parse(Float64, tokens[15]),
            parse(Float64, tokens[16]),
            parse(Float64, tokens[17]),
            parse(Float64, tokens[18]),
            parse(Float64, tokens[19]),
            parse(Float64, tokens[20]),
            parse(Float64, tokens[21]),
            parse(Float64, tokens[22]),
            parse(Float64, tokens[23]),
            parse(Int, tokens[24])
        )
        return vel
    end
end
